--!strict

local KeybindIds = {
	Sprint = "Sprint",
	Jump = "Jump",
	Interact = "Interact",
	ThirdPersonCameraLock = "ThirdPersonCameraLock",

	AbilitySlot1 = "AbilitySlot1",
	AbilitySlot2 = "AbilitySlot2",
	AbilitySlot3 = "AbilitySlot3",
	AbilitySlot4 = "AbilitySlot4",
	AbilitySlot5 = "AbilitySlot5",

	HudWeapon1 = "HudWeapon1",
	HudWeapon2 = "HudWeapon2",
	HudSwapWeapons = "HudSwapWeapons",
	HudFists = "HudFists",
	HudQuickUse = "HudQuickUse",
	HudFlashlight = "HudFlashlight",

	ToggleLoadout = "ToggleLoadout",
	ToggleMap = "ToggleMap",
}

return table.freeze(KeybindIds)
